#! /bin/sh -e

if [ "$SNAP_ARCH" = "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" = "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

# fonts
export XDG_DATA_HOME=$SNAP/usr/share
export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf

# theme
export GTK2_RC_FILES=$SNAP/gtkrc

export GTK_PATH=$SNAP/usr/lib/$ARCH/gtk-2.0

# gdk pixbuf
export GDK_PIXBUF_MODULE_FILE=$SNAP_USER_DATA/.gdk-pixbuf-loaders.cache
export GDK_PIXBUF_MODULEDIR=$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/2.10.0/loaders
$SNAP/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $GDK_PIXBUF_MODULE_FILE

XDMCP=""

while [ -z "${XDMCP}" ]; do
    XDMCP=$(yad --maximized --entry --entry-label="XDMCP Server IP" --borders=300)
    #XDMCP=$(yad --center --entry --entry-label="XDMCP Server IP" --no-buttons --borders=250)
done

Xephyr -retro -fullscreen -query "${XDMCP}" :0
